# Generated by Django 3.2.7 on 2021-09-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_useractivitysummary_time_logged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitysummary',
            name='activity_time',
            field=models.IntegerField(default=0, verbose_name='activity_time'),
        ),
    ]
