# Generated by Django 3.2.7 on 2021-09-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20210914_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='useractivitysummary',
            name='total_login',
        ),
        migrations.AddField(
            model_name='useractivitysummary',
            name='activity',
            field=models.CharField(default='activity', max_length=200),
        ),
    ]
